name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/mi-api:${GITHUB_SHA}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy mi-api --image gcr.io/${{ secrets.GCP_PROJECT }}/mi-api:${GITHUB_SHA} --platform managed --region us-central1
